name: run-ci-checks
run-name: ${{ github.actor }} - Running checks on the code ğŸš€
on:
  workflow_call:

jobs:
  Basic-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "--------------------------------------------------------------------------------------"
      - run: echo "ğŸ‘‹ The repository has been checked out successfully."
      - run: echo "Go linting will be added in the future."
      - run: echo "--------------------------------------------------------------------------------------"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
